from collections.abc import Sequence
from typing import cast

from aws_cdk import CustomResource, Duration, Stack
from aws_cdk.aws_ec2 import ISecurityGroup, IVpc, SubnetSelection
from aws_cdk.aws_lambda import Runtime
from aws_cdk.aws_rds import IDatabaseCluster
from aws_cdk.aws_secretsmanager import ISecret, Secret, SecretStringGenerator
from aws_cdk.custom_resources import Provider

from callsy_cdk.db_readonly_role.function import DatabaseReadonlyRoleFunction

# Construct id of the resource, and the stem of every child it builds.
DEFAULT_ID = "DatabaseReadonlyRole"

# Name of the Postgres role, and the username stored in its secret.
ROLE_NAME = "readonly"

# Length of the generated password.
PASSWORD_LENGTH = 32

# Connections the role may hold at once, so one client cannot eat the cluster's budget.
CONNECTION_LIMIT = 5

# How long the role may hold a connection or a lock, set on the role itself.
STATEMENT_TIMEOUT = "30s"
IDLE_TRANSACTION_TIMEOUT = "60s"
LOCK_TIMEOUT = "5s"

# Description of the generated secret.
SECRET_DESCRIPTION = "Credentials of the read-only role on the database."


class DatabaseReadonlyRole(CustomResource):
    """
    Postgres role that reads every table and writes nothing.

    Its password is generated by Secrets Manager and is readable only there.
    Removing this construct and deploying drops the role.
    """

    def __init__(
            self,
            scope: Stack,
            cluster: IDatabaseCluster,
            database_name: str,
            *,
            id: str = DEFAULT_ID,
            role_name: str = ROLE_NAME,
            master_secret: ISecret | None = None,
            secret_name: str | None = None,
            secret_description: str = SECRET_DESCRIPTION,
            password_length: int = PASSWORD_LENGTH,
            connection_limit: int = CONNECTION_LIMIT,
            statement_timeout: str = STATEMENT_TIMEOUT,
            idle_transaction_timeout: str = IDLE_TRANSACTION_TIMEOUT,
            lock_timeout: str = LOCK_TIMEOUT,
            function_name: str | None = None,
            runtime: Runtime | None = None,
            memory_size: int | None = None,
            timeout: Duration | None = None,
            docker_image: str | None = None,
            vpc: IVpc | None = None,
            vpc_subnets: SubnetSelection | None = None,
            security_groups: Sequence[ISecurityGroup] | None = None
    ) -> None:
        # An imported cluster carries no secret, so the credentials can also be handed over.
        if master_secret is None:
            master_secret = cast(ISecret | None, getattr(cluster, "secret", None))

        if master_secret is None:
            raise ValueError(
                "The cluster carries no master secret. Pass `master_secret` with the "
                "credentials the role is created under."
            )

        # Credentials of the role, generated at create and never touched by hand.
        #
        # The four templated keys are the shape of the cluster's own master secret, so the
        # secret speaks the database's vocabulary rather than any one consumer's.
        #
        # host is the reader endpoint. Every consumer of this secret only reads, and on a
        # cluster that gains a replica the endpoint starts routing to it with no change
        # here. It is a routing choice and not a safety one: on a single-instance cluster
        # the reader endpoint is fully writable, and the role is what stops a write.
        secret = Secret(
            scope=scope,
            id=f"{id}Secret",
            # Name it when another project looks the secret up by name rather than by arn.
            secret_name=secret_name,
            description=secret_description,
            generate_secret_string=SecretStringGenerator(
                # Rendered by the stack so the endpoint resolves at deploy time.
                secret_string_template=Stack.of(scope).to_json_string({
                    "host": cluster.cluster_read_endpoint.hostname,
                    "port": cluster.cluster_read_endpoint.port,
                    "dbname": database_name,
                    "username": role_name
                }),
                generate_string_key="password",
                password_length=password_length,
                # Keeps the password usable in a connection string without escaping.
                exclude_punctuation=True
            )
        )

        # Runs the SQL. It needs both secrets: the master to connect, the role's to set it.
        function = DatabaseReadonlyRoleFunction(
            scope=scope,
            id=f"{id}Function",
            function_name=function_name,
            runtime=runtime,
            memory_size=memory_size,
            timeout=timeout,
            docker_image=docker_image,
            vpc=vpc,
            vpc_subnets=vpc_subnets,
            security_groups=security_groups
        )

        master_secret.grant_read(function)
        secret.grant_read(function)

        # No completion handler, so the provider is synchronous and builds no waiter.
        provider = Provider(
            scope=scope,
            id=f"{id}Provider",
            on_event_handler=function
        )

        # Host is the writer endpoint here. CREATE ROLE is a write and only the writer
        # accepts it, while the secret above points every reader at the reader endpoint.
        super().__init__(
            scope=scope,
            id=id,
            service_token=provider.service_token,
            resource_type="Custom::DatabaseReadonlyRole",
            properties={
                "Host": cluster.cluster_endpoint.hostname,
                "Port": cluster.cluster_endpoint.port,
                "Database": database_name,
                "RoleName": role_name,
                "MasterSecretArn": master_secret.secret_arn,
                "RoleSecretArn": secret.secret_arn,
                "ConnectionLimit": connection_limit,
                "StatementTimeout": statement_timeout,
                "IdleTransactionTimeout": idle_transaction_timeout,
                "LockTimeout": lock_timeout
            }
        )

        self.secret = secret
        self.role_name = role_name
        self.function = function
